Repository zantec/yarg-server, pull requests merged in 2019-03, with the labels that each got.

#2 Added More User Endpoints
  .gitignore
  TestFunctions.js
  database/index.js
  database/index.test.js
  server/index.js
  server/index.test.js
Labels: review

#4 User endpoints - Get/Add/Update/Login/SignUp Users - Get/Add/Delete Treasures - Get/Add/Delete Riddles
  TestFunctions.js
  database/index.js
  server/index.js
Labels: endpoint, review

#6 User endpoints - Added more tests
  database/index.js
  database/index.test.js
  server/index.js
Labels: review, tests

#9 User endpoints
  database/index.js
  package-lock.json
  package.json
  server/index.js
  server/index.test.js
Labels: endpoint, review, tests

#10 User endpoints - Added A Lot of Tests
  server/index.js
  server/index.test.js
Labels: endpoint, review, tests

#11 User endpoints - Tests for db helpers
  TestFunctions.js
  database/QuarterPirates.sql
  database/index.js
  database/index.test.js
  server/index.test.js
Labels: endpoint, review, tests

#12 Add endpoints for getting riddles and treasures by zipcode
  TestFunctions.js
  database/QuarterPirates.sql
  database/index.js
  server/index.js
Labels: endpoint, review

#13 User endpoints - Filter out signed in user riddles and treasures
  database/index.js
  server/index.js
Labels: endpoint, review

#14 Refractor Deleting Treasures and Deleting Riddles
  TestFunctions.js
  database/QuarterPirates.sql
  database/index.js
Labels: endpoint

#15 Front - Fix to delete endpoint
  server/index.js
Labels: endpoint, review

#16 Bug Fix
  database/index.js
Labels: endpoint, review

#17 Front Better Fix
  database/index.js
Labels: endpoint

#18 Server Gold Is Now Negative On Database Drop and Reload
  database/QuarterPirates.sql
  server/index.js
Labels: review

#19 Leaderboard
  server/index.js
Labels: endpoint, review

#20 add server endpoint to recieve stats with minor functionality
  server/index.js
Labels: review

#21 Helper Function For Getting Filtered User's
  TestFunctions.js
  database/QuarterPirates.sql
  database/index.js
  package-lock.json
  package.json
Labels: review

#22 leaderboard endpoint and stats endpoint send correct information
  server/index.js
Labels: review

#23 New User Stats And Change Default Image For Users
  TestFunctions.js
  database/QuarterPirates.sql
  database/index.js
  server/index.js
Labels: review

#24 Backend Update of Helper Functions
  TestFunctions.js
  database/QuarterPirates.sql
  database/index.js
Labels: review

#26 Created Endpoint That Allows Updating Any Numeric User Stat
  database/index.js
  server/index.js
Labels: endpoint, review

#27 Small Delete BugFix
  server/index.js
Labels: bug, endpoint, review
